# Generated by Django 6.0.3 on 2026-03-22 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0004_alter_fieldmanager_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='itime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_exported', models.BooleanField(default=False, verbose_name='Exported to Payroll')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='staff.validationteammember', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'iTime Record',
                'verbose_name_plural': 'iTime Records',
            },
        ),
    ]
