# Generated by Django 6.0.3 on 2026-03-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itime', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itime',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='daily_attendances', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='itime',
            unique_together={('employee', 'date')},
        ),
    ]
