# Generated by Django 6.0.3 on 2026-03-23 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itime', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itime',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
