# Generated by Django 6.0.3 on 2026-03-23 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('staff', '0004_alter_fieldmanager_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='field_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to='staff.fieldmanager', verbose_name='Field Manager'),
        ),
    ]
