# Generated by Django 6.0.3 on 2026-03-23 07:21

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_field_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_files',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.project_files_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv', 'mtt', 'mdd', 'ddf'])]),
        ),
    ]
