# Generated by Django 6.0.3 on 2026-03-24 06:42

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_project_files_projectfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfiles',
            name='file',
            field=models.FileField(upload_to=projects.models.project_files_path),
        ),
    ]
