# Generated by Django 6.0.3 on 2026-03-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Manager Name')),
            ],
            options={
                'verbose_name': 'Field Manager',
                'verbose_name_plural': 'Field Managers',
                'ordering': ['name'],
            },
        ),
    ]
