# Generated by Django 6.0.3 on 2026-03-22 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_email'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmanager',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fieldmanager',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_manager_info', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='fieldmanager',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Field Manager Name'),
        ),
    ]
