# Generated by Django 6.0.3 on 2026-03-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role'),
        ('staff', '0002_fieldmanager_email_fieldmanager_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Employee ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Work Email')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_info', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Validation Team Member',
                'verbose_name_plural': 'Validation Team Members',
                'ordering': ['name'],
            },
        ),
    ]
