# Generated by Django 6.0.3 on 2026-03-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_iTime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('field_manager', 'Field Manager'), ('validator', 'Validation Team')], default='viewer', max_length=20),
        ),
    ]
