# Generated by Django 6.0.3 on 2026-03-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_can_access_itime_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('field_manager', 'Field Manager'), ('validator', 'Validation Team')], default='viewer', max_length=20),
        ),
    ]
