# Generated by Django 6.0.3 on 2026-03-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_can_access_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='can_access_Project',
            new_name='can_access_Projects_tool',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='can_access_iTime',
            new_name='can_access_iTime_tool',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='can_access_time_check',
            new_name='can_access_time_check_tool',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='can_marks_iTime_as_exported',
            new_name='can_mark_iTime_as_exported',
        ),
    ]
