# Generated by Django 6.0.3 on 2026-03-17 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldmanager',
            options={'ordering': ['name'], 'verbose_name': 'Field Manager', 'verbose_name_plural': 'Field Managers'},
        ),
    ]
