# Generated by Django 6.0.3 on 2026-03-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeCheck', '0002_alter_fieldmanager_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCheckValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_manager_name_snapshot', models.CharField(max_length=150, verbose_name='Field Manager Name at Upload')),
                ('project_names', models.JSONField(default=list, verbose_name='Project Names (Scripts)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Validation Date')),
                ('overlap_report', models.JSONField(blank=True, null=True, verbose_name='Time Overlaps')),
                ('daily_count_report', models.JSONField(blank=True, null=True, verbose_name='Daily Interview Count')),
                ('out_working_hours_report', models.JSONField(blank=True, null=True, verbose_name='Outside Working Hours')),
                ('loi_report', models.JSONField(blank=True, null=True, verbose_name='Length of Interview (LOI)')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Original Data')),
                ('field_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='TimeCheck.fieldmanager', verbose_name='Field Manager')),
            ],
            options={
                'verbose_name': 'Validation Result',
                'verbose_name_plural': 'Validation Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
