# Generated by Django 6.0.3 on 2026-03-17 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeCheck', '0003_timecheckvalidationresult'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecheckvalidationresult',
            name='field_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='staff.fieldmanager', verbose_name='Field Manager'),
        ),
        migrations.AlterModelOptions(
            name='timecheckvalidationresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Time Check Validation Result', 'verbose_name_plural': 'Time Check Validation Results'},
        ),
        migrations.DeleteModel(
            name='FieldManager',
        ),
    ]
