# Generated by Django 6.0.3 on 2026-03-18 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeCheck', '0004_alter_timecheckvalidationresult_field_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timecheckvalidationresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_check_validations', to=settings.AUTH_USER_MODEL, verbose_name='Processed By (User)'),
        ),
    ]
