# Generated by Django 6.0.3 on 2026-03-18 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeCheck', '0005_timecheckvalidationresult_user'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecheckvalidationresult',
            name='field_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_results', to='staff.fieldmanager', verbose_name='Field Manager'),
        ),
    ]
