# Generated by Django 6.0.3 on 2026-03-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeCheck', '0006_alter_timecheckvalidationresult_field_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecheckvalidationresult',
            name='daily_count_report',
            field=models.TextField(blank=True, null=True, verbose_name='Daily Interview Count'),
        ),
        migrations.AlterField(
            model_name='timecheckvalidationresult',
            name='loi_report',
            field=models.TextField(blank=True, null=True, verbose_name='Length of Interview (LOI)'),
        ),
        migrations.AlterField(
            model_name='timecheckvalidationresult',
            name='out_working_hours_report',
            field=models.TextField(blank=True, null=True, verbose_name='Outside Working Hours'),
        ),
        migrations.AlterField(
            model_name='timecheckvalidationresult',
            name='overlap_report',
            field=models.TextField(blank=True, null=True, verbose_name='Time Overlaps'),
        ),
        migrations.AlterField(
            model_name='timecheckvalidationresult',
            name='project_names',
            field=models.TextField(default=list, verbose_name='Project Names (Scripts)'),
        ),
        migrations.AlterField(
            model_name='timecheckvalidationresult',
            name='raw_data',
            field=models.TextField(blank=True, null=True, verbose_name='Original Data'),
        ),
    ]
