# Generated by Django 6.0.3 on 2026-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeCheck', '0007_alter_timecheckvalidationresult_daily_count_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecheckvalidationresult',
            name='project_names',
            field=models.JSONField(default=list, verbose_name='Project Names (Scripts)'),
        ),
    ]
